spring.application.name=AirVision
spring.datasource.url=jdbc:postgresql://db:5432/airvision
spring.datasource.username=airvision
spring.datasource.password=airvision
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
